### ISSUE TITLE
XGBoostError: [17:01:28] ../src/data/data.cc:458: Check failed: valid: Label contains NaN, infinity or a value too large.

### ISSUE THREAD

**Issue by sustech-lz** [IHIaadj/ranked_nas#1]

**Comment by ZhengLI-Sustech** [comment]
from pymoo.operators.sampling.random_sampling import FloatRandomSampling
# Generate Initial samples
# X_init, Y_init = generate_initial_samples_SS(problem, n_sample=100)
sampling = FloatRandomSampling()
X_init = sampling.do(problem, 100).get("X")
Y_init= problem.evaluate(X_init, return_values_of=['F'])
print(Y_init)
#solve
solution = hyt_opt.solve(X_init, Y_init)

for _ in range(20):
  # get new design samples and corresponding performance
  X_next, Y_next = next(solution)
  #print(calc_pareto(problem))


The first demension of Y_init is Nan, how can we fix this issue?
